version: '3'
services:
    categorize:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8081:80
        networks:
            - identity_app-shared
networks:
    identity_app-shared:
        external: true
