# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - mongodb
        networks:
            - identity_app-shared
            - sail
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
          - PUID=1000
          - PGID=1000
        volumes:
          - 'sailmongodb:/var/lib/mongodb'
        ports:
          - 27017:27017
        restart: unless-stopped
        networks:
          - sail
networks:
    sail:
        driver: bridge
    identity_app-shared:
        external: true
volumes:
    sailmongodb:
      driver: local
