# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0.23'
        ports:
            - '33061:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        #volumes:
            #- './storage/dbdata:/var/lib/mysql'
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
