# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - mysql
            - mongodb
        networks:
            - identity_app-shared
            - sail
    mysql:
        image: 'mysql:8.0.23'
        ports:
            - '33061:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
          - 'sailmysql:/var/lib/mysql'
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
        networks:
            - sail
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
          - PUID=1000
          - PGID=1000
        volumes:
          - 'sailmongodb:/var/lib/mongodb'
        ports:
          - 27017:27017
        restart: unless-stopped
        networks:
          - sail
networks:
    sail:
        driver: bridge
    identity_app-shared:
        external: true
volumes:
    sailmysql:
        driver: local
    sailmongodb:
      driver: local
