# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: "Deploy Infrastructure"
  inputs:
    azureSubscription: 'dev-connection'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az deployment group create --resource-group 'dev' --name infrastructure \
        --template-file ./storage_account.bicep
