# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

parameters:
  - name: resourceGroup
    default: 'dev'

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: "Deploy Infrastructure"
  inputs:
    azureSubscription: '$(subscriptionId)'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az deployment group create --resource-group ${{ parameters.resourceGroup }} --name infrastructure \
        --template-file ./infrastructure/storage_account.bicep
